# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WirVsVirus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReachabilitySwift', '~> 4.3.1'
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireNetworkActivityLogger', '~> 2.4.0'
  pod 'SDWebImage'
  pod 'JWTDecode', '~> 2.4'
  pod "SwiftSignatureView"

  # Pods for WirVsVirus

  target 'WirVsVirusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WirVsVirusUITests' do
    # Pods for testing
  end

end
